import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "./components/Navbar";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Tabbed Content Builder for LMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} antialiased font-(family-name:--font-poppins)`}
      >
        <ThemeProvider enableSystem>
          <Navbar />
          <hr className="hidden dark:block" />
          {children}
          <hr className="hidden dark:block" />
        </ThemeProvider>
      </body>
    </html>
  );
}
